services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
        - .:/app
        - /var/run/docker.sock:/var/run/docker-host.sock
        - '/app/node_modules'
        ports:
        - 19000:19000
        - 19001:19001
        - 19002:19002
        - 19003:19003
        - 19004:19004
        - 19005:19005
        - 19006:19006
        environment: 
        - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.21
        - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
